### ISSUE TITLE
REQUEST: Add SimplyNZBs to the 'Add new indexer' drop-down menu

### ISSUE THREAD

**Issue by SimplyNZBs** [theotherp/nzbhydra#253]
Please can you add SimplyNZBs to the 'Add new indexer' drop-down menu

**Comment by theotherp** [comment]
If you tell me the relevant data, sure.

**Comment by SimplyNZBs** [comment]
Thanks :)

Name: SimplyNZBs
Host: https://simplynzbs.com
Enable for: Internal and API Searches
Search IDs: IMDB, TVRage, TMDB, TVDB, TVMaze
Search Types: Movies, TV

**Comment by albino1** [comment]
@SimplyNZBs can you take a look at https://github.com/theotherp/nzbhydra/issues/204 and maybe between you and @theotherp you guys can straighten out the best way for your indexer to return correct results.  Thanks.

**Comment by SimplyNZBs** [comment]
I think I know the issue with #204, was looking at it yesterday but didn't have time to fix it, should hopefully get it sorted out this week

**Comment by albino1** [comment]
Great, I look forward to re-enabling your indexer ;)

**Comment by theotherp** [comment]
@SimplyNZBs That would be awesome.

**Comment by SimplyNZBs** [comment]
#204 should be fixed now :)

**Comment by theotherp** [comment]
Great. Could you tell me roughly what the problem was and what you did to solve it? So we could tell other indexers with the same problem.

**Comment by SimplyNZBs** [comment]
Change the search type in nZEDb to not use the default fulltext indexing and use Sphinx instead

**Comment by albino1** [comment]
Looks good @SimplyNZBs, thanks!

**Comment by mill99** [comment]
Hi all,

The problem still appears on my NzbHydra.

Someone could confirm that the problem is solved ?

Ty

**Comment by albino1** [comment]
Just tried my previous test case from #204 and it returned correct results.  Can you give an example search where it fails?
